# Generated by Django 4.1.4 on 2023-03-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_room_current_song"),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlists",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_id", models.CharField(max_length=50)),
                ("song_name", models.CharField(max_length=50)),
            ],
        ),
    ]
