# Generated by Django 4.1.4 on 2023-03-29 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_playlists"),
    ]

    operations = [
        migrations.RenameField(
            model_name="playlists",
            old_name="song_id",
            new_name="Playlist_id",
        ),
        migrations.RenameField(
            model_name="playlists",
            old_name="song_name",
            new_name="Playlist_name",
        ),
        migrations.CreateModel(
            name="Sonsg",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("song_id", models.CharField(max_length=50)),
                ("song_name", models.CharField(max_length=50)),
                (
                    "Playlist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.playlists"
                    ),
                ),
            ],
        ),
    ]
