# Generated by Django 4.1.4 on 2023-03-29 19:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_rename_song_id_playlists_playlist_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sonsg",
            new_name="Songs",
        ),
    ]
