# Generated by Django 4.1.4 on 2023-03-29 19:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_rename_sonsg_songs"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Songs",
        ),
    ]
